name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter_hooks: 0.21.2
  flutter_painter_v2:
    path: ../
  flutter_riverpod: 2.6.1
  hooks_riverpod: 2.6.1
  image: 4.5.4
  image_picker: 1.2.0
  json_annotation: 4.9.0
  mime: 2.0.0
  path_provider: 2.1.5
  permission_handler: 12.0.1
  riverpod_annotation: 2.6.1


dev_dependencies:
  analyzer: 7.6.0
  auto_route_generator: 10.0.1
  build_runner: 2.5.4
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.9.5
  mocktail: ^0.3.0
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5

flutter:
  uses-material-design: true
