name: flutter_painter_v2
version: 2.1.0+1
description: A Flutter widget to draw scribbles, text, shapes and images on a background image or color
homepage: https://github.com/hatemragab/flutter_painter_v2
repository: https://github.com/hatemragab/flutter_painter_v2
issue_tracker: https://github.com/hatemragab/flutter_painter_v2/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_exif_rotation: 0.5.2
  hooks_riverpod: 2.6.1
  image: 4.5.4
  image_background_remover: 1.0.0
  image_cropper: 9.1.0
  path_provider: 2.1.5
  riverpod_annotation: 2.6.1
  collection: ^1.18.0

dev_dependencies:
  json_serializable: 6.9.5
  build_runner: 2.5.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.6.5
  riverpod_lint: 2.6.5
  mocktail: ^0.3.0

flutter:
